Gemfile, Gemfile.lock, config/database.yml
* 在 Gemfile 安裝 pg（PostgreSQL 的 adapter）
* 設定 database.yml
* 以 rails db:create 建立資料庫
=> 改用PostgreSQL為資料庫

app/models/card.rb, app/models/setbox.rb, db/migrate/20190919075953_create_setboxes.rb, db/migrate/20190919080234_create_cards.rb, db/schema.rb, test/fixtures/cards.yml, test/fixtures/setboxes.yml, test/models/card_test.rb, test/models/setbox_test.rb
=> 007 models 已建立完成

app/assets/javascripts/setboxes.coffee, app/assets/stylesheets/setboxes.scss, app/controllers/setboxes_controller.rb, app/helpers/setboxes_helper.rb
=> 008 建立 setbox controller

app/controllers/application_controller.rb, app/controllers/setboxes_controller.rb, app/controllers/users/confirmations_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/controllers/users/passwords_controller.rb, app/controllers/users/registrations_controller.rb, app/controllers/users/sessions_controller.rb, app/controllers/users/unlocks_controller.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/setboxes/_form.html.erb, app/views/setboxes/edit.html.erb, app/views/setboxes/new.html.erb, app/views/shared/frontend/_navbar.html.erb, config/routes.rb
修正devise edit/new頁面按鈕
好像有點弄到 014_修改個人資料功能(Devise)～
=> 009 crud 4

app/views/users/registrations/edit.html.erb, app/views/users/registrations/new.html.erb, app/views/users/sessions/new.html.erb
=> 026 修正登入註冊畫面

app/controllers/setboxes_controller.rb, app/models/setbox.rb, app/views/setboxes/search.html.erb, app/views/shared/frontend/_navbar.html.erb, config/routes.rb
*新增search頁面路徑
*修改nav bar的搜尋按鈕，連結至search頁面
*setbox.rb加上搜尋條件
*setbox_controller加上search方法
*search頁面顯示搜尋前、搜尋後結果（目前只顯示學習集名稱）
=> 017_搜尋單字功能

app/assets/stylesheets/application.scss, app/views/users/registrations/edit.html.erb, app/views/users/shared/_links.html.erb
照著 登入/註冊 共用版面套的 之後有時間可以好好的修改樣子
=> 014 修改個人資料頁面（尚須修改）

app/assets/stylesheets/application.scss, app/views/setboxes/_card_fields.html.erb, app/views/setboxes/_form.html.erb, app/views/setboxes/new.html.erb
=> 023 新增學習集簡單套版(尚需修改)

app/controllers/setboxes_controller.rb, app/views/setboxes/search.html.erb
* 將原本的table改用bootstrap的card套版
* 搜尋欄位尚需美化、置中的方法需再調整
* 學習集顏色、尺寸可再調整
=> 028 建立搜尋頁面（尚須修改）

app/controllers/setboxes_controller.rb, app/views/setboxes/index.html.erb
=> 021_建立首頁（尚須修改）

app/views/setboxes/_show_fields.html.erb, app/views/setboxes/show.html.erb
* 建立基本單詞卡列表頁面(show)，尚欠中間的卡片，各按鈕連結
=> 024_單詞卡列表頁面（尚須修改）

app/assets/javascripts/application.js, app/assets/javascripts/myjs.js, app/views/setboxes/_show_fields.html.erb, app/views/setboxes/home.html.erb, app/views/setboxes/show.html.erb
進入 new 畫面時 需要 按下重新整理 頁面才能 正常運作
似乎是因為此頁面是以 render 出來的，而我們要以動態的方式取綁定
所以還要再修正
=> 018 text to speak (尚需修改)

app/controllers/setboxes_controller.rb, app/views/setboxes/pullreq.html.erb, app/views/setboxes/show.html.erb, config/routes.rb
* 建立暫時性的PR頁面
* 修改show頁面的按鈕連結（分享、刪除這兩個以外的按鈕）
=> 025_建立PR頁面（尚須修改）

app/views/setboxes/home.html.erb, app/views/setboxes/show.html.erb
=> 學習集分享完成 QRCODE 還有 BUG

app/assets/stylesheets/application.scss, app/assets/stylesheets/helloword.scss, app/assets/stylesheets/setboxes.scss, app/controllers/setboxes_controller.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/layouts/application.html.erb, app/views/setboxes/edit.html.erb, app/views/setboxes/home.html.erb, app/views/setboxes/index.html.erb, app/views/setboxes/search.html.erb, app/views/shared/frontend/_footer.html.erb, app/views/shared/frontend/_navbar.html.erb, app/views/users/registrations/edit.html.erb, app/views/users/registrations/new.html.erb, app/views/users/sessions/new.html.erb
- 首頁排版
- search版面簡單排版+首頁也加入search
- 021 修正登入/註冊背景顏色+搜尋sample(9)
- footer位置更改:首頁/登入/註冊
=> 021 home page trial 2

app/assets/javascripts/myjs.js, app/views/setboxes/home.html.erb
=> 018 發音功能 完成

app/assets/stylesheets/application.scss, app/views/setboxes/home.html.erb, app/views/setboxes/show.html.erb
- 修改 View 內的排版 + Carousel
- Carousel讀取後端的資料還未完成 尚須修改
=> 024 show page trial 2

app/controllers/setboxes_controller.rb, app/views/setboxes/show.html.erb, config/routes.rb
=> 016_學習集複製功能_未修版

app/controllers/setboxes_controller.rb, app/models/setbox.rb, app/views/setboxes/show.html.erb, app/views/setboxes/write.html.erb, config/routes.rb
* 修改為可搜尋：學習集名稱、單字、定義
* 新增筆試頁面（簡報時demo用的假頁面）
=> 034_建立暫時筆試頁面

config/environments/production.rb
=> 000_Hiroku Production 檔案修正

config/environments/production.rb
=> 000_寄信功能上線更改設定

config/environments/production.rb
=> 000_寄信功能修正＿02

config/environments/production.rb, config/environments/test.rb, config/initializers/devise.rb
=> 000 fb login online

config/initializers/devise.rb
=> 000_FB 登入修正02

app/models/user.rb
=> 000_登入錯誤修正

app/views/layouts/application.html.erb, app/views/setboxes/index.html.erb
- viewport
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=1">
=> 040 application.html.erb viewport

app/controllers/setboxes_controller.rb, app/views/setboxes/answer.html.erb, app/views/setboxes/show.html.erb, app/views/setboxes/write.html.erb, config/routes.rb
* 完成測驗基本功能（只能判斷是否全對狀況）
* 加上隨機選取5個單字功能
=> 033_基本筆試測驗功能

app/views/setboxes/answer.html.erb, app/views/setboxes/write.html.erb
=> 040 write RWD 

app/views/setboxes/show.html.erb
=> 042_刪除按鈕只會出現在學習集主人頁面上

app/controllers/setboxes_controller.rb, app/views/setboxes/write.html.erb, app/views/setboxes/write.js.erb, config/routes.rb
=> 033_紅字會在重新輸入答案時清空

Gemfile, Gemfile.lock, app/controllers/api/v1/authentication_controller.rb, app/controllers/api/v1/setboxes_controller.rb, app/controllers/api_controller.rb, app/controllers/setboxes_controller.rb, app/models/user.rb, app/views/setboxes/index.html.erb, config.ru, config/application.rb, config/routes.rb, db/migrate/20191007041459_add_auth_token_on_users.rb, db/schema.rb
=> 041 chrome extension

app/controllers/application_controller.rb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/setboxes/_card_fields.html.erb, app/views/setboxes/_form.html.erb, app/views/setboxes/_perfect.html.erb, app/views/setboxes/_unperfect.html.erb, app/views/setboxes/edit.html.erb, app/views/setboxes/home.html.erb, app/views/setboxes/index.html.erb, app/views/setboxes/new.html.erb, app/views/setboxes/search.html.erb, app/views/setboxes/show.html.erb, app/views/setboxes/write.html.erb, app/views/shared/frontend/_navbar.html.erb, app/views/users/registrations/edit.html.erb, app/views/users/registrations/new.html.erb, app/views/users/sessions/new.html.erb, config/application.rb, config/initializers/locale.rb, config/locales/en.yml, config/locales/zh.yml, config/routes.rb
* 建立i18英文版
* 有"#{card.card_def}"時不知道怎麼寫（write、search頁面）
* 在英文版search頁面按下search後會跳回中文版
* 登入頁面的Remember me不知在哪裡改
* Google登入的Oauth2待修正
=> 044_建立i18英文版

Gemfile
=> 000_加入Font Awesom Gem

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/views/shared/frontend/_navbar.html.erb, config.ru
=> google extension + lelecoco

.gitignore, config/google_cloud.json
=> 000 git ignore updated

app/controllers/setboxes_controller.rb, app/views/setboxes/home.html.erb, app/views/shared/frontend/_navbar.html.erb
- Navbar 背景顏色 文字修改
- home頁面+new （如果學習集<1 會render new頁面
=> 051 Navbar RWD home頁面+new --icon

app/controllers/setboxes_controller.rb, app/views/setboxes/show.html.erb
- fix 進入show頁面會噴錯問題 
- before_action login
=> 051 進入show之前要登入 解決controller出錯

Gemfile, Gemfile.lock
=> 043 safety problem

app/assets/javascripts/myjs.js, app/controllers/application_controller.rb, app/views/setboxes/home.html.erb
=> 修正 發音按鈕壞掉+登入後倒回首頁

app/views/setboxes/_noresult.html.erb, app/views/setboxes/search.html.erb
=> 017_修正搜不到頁面跑版

app/views/layouts/application.html.erb
- title 改為 helloword
- head icon 更新!!!
=> 051 title->helloword head->icon

app/views/devise/sessions/new.html.erb, app/views/users/registrations/edit.html.erb, app/views/users/registrations/new.html.erb
=> 055 footer跑版處理

Gemfile, Gemfile.lock
=> 043_更新rubyzip gem

.gitignore, config/cloud_translate.json
=> 000 google credentials
